
/*
 * AcctLogin.java
 *
 * Created on 21-Sept-2011, 09:11:06
 */
package com.ourteam.yippySMS.view;

/**
 *
 * @author dantheta
 */
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;

public class AcctLogin extends javax.swing.JDialog implements RootPaneContainer {

    String cat;

    public void createDesiredBorder(JButton jbtn) {
        jbtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED),
                javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(
                2, 2, 2, 2, new java.awt.Color(0, 0, 0)),
                javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED))),
                javax.swing.BorderFactory.createBevelBorder(
                javax.swing.border.BevelBorder.RAISED)));
    }

    private static Connection getConnection() {
        Connection con = null;
        String url = "jdbc:mysql://localhost:3306/SMS";
        String driver = "com.mysql.jdbc.Driver";
        String user = "root";
        String passwd = "";
        try {
            Class.forName(driver);
            con = DriverManager.getConnection(url, user, passwd);
        } catch (ClassNotFoundException e) {
            System.out.println("Unable to locate class");
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, " Database not connected");
            System.exit(0);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, " Database not connected");
            System.exit(0);
        }
        return con;
    }

    /** Creates new form AcctLogin */
    public AcctLogin(JFrame frame, String str) {

        addWindowListener(new WindowAdapter() {

            public void windowClosing(WindowEvent e) {
                buttonCancel.doClick();
            }
        });

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usernameTextBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordTextBox = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCHOOL MANAGEMENT SYSTEM");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 204, 255));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        usernameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextBoxActionPerformed(evt);
            }
        });
        usernameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameTextBoxKeyPressed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        passwordTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextBoxActionPerformed(evt);
            }
        });
        passwordTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTextBoxKeyPressed(evt);
            }
        });

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passwordTextBox)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addComponent(usernameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin)
                    .addComponent(buttonCancel)
                    .addComponent(backButton)))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addteacher.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_usernameTextBoxActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        boolean verify = false;
        String user = usernameTextBox.getText();
        String passwd = passwordTextBox.getText();
        if (user.equals("") || passwd.equals("")) {
            JOptionPane.showMessageDialog(AcctLogin.this, "Sorry! You must enter a Username and Password to login");
            usernameTextBox.requestFocus();
        } else {
            verify = true;
            this.dispose();
            //JFrame frame = new JFrame();
            AdminMainView teacherBtns = new AdminMainView();
            teacherBtns.teacherBtnsEnabled();
            //new QtityWindow2().setVisible(true);
        }
}//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
        // TODO add your handling code here:
}//GEN-LAST:event_buttonCancelActionPerformed

    private void passwordTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextBoxKeyPressed
        // TODO add your handling code here
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            boolean verify = false;
            String user = usernameTextBox.getText();
            String passwd = passwordTextBox.getText();
            if (user.equals("") || passwd.equals("")) {
                JOptionPane.showMessageDialog(AcctLogin.this, "Sorry! You must enter a Username and Password to login ");
                usernameTextBox.requestFocus();
            } else {
                Connection con = getConnection();
                try {
                    ResultSet rows;
                    Statement s = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    String select = "Select * from teacherLogin;";
                    rows = s.executeQuery(select);
                    while (rows.next()) {
                        String username = rows.getString("Username");
                        String password = rows.getString("Password");
                        if (user.equals(username) && passwd.equals(password)) {
                            verify = true;
                            this.dispose();
                            JFrame frame = new JFrame();
                            AdminMainView teacherBtns = new AdminMainView();
                            teacherBtns.teacherBtnsEnabled();
                            // new QtityWindow2().setVisible(true);
                            break;
                        }
                    }
                    if (verify == false) {
                        verify = false;
                        JOptionPane.showMessageDialog(AcctLogin.this, "Access Denied!  You do not have permission to access this Category");
                        usernameTextBox.setText("");
                        passwordTextBox.setText("");
                        usernameTextBox.requestFocus();
                    }
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
                if (verify == false) {
                    JOptionPane.showMessageDialog(AcctLogin.this, "Access Denied!  Wrong Username or Password");
                    usernameTextBox.setText("");
                    passwordTextBox.setText("");
                    usernameTextBox.requestFocus();
                }     // TODO add your handling code here:
            }
        }

        if (key == KeyEvent.VK_UP) {
            usernameTextBox.grabFocus();
        }
        if (key == KeyEvent.VK_KP_UP) {
            usernameTextBox.grabFocus();
        }
    }//GEN-LAST:event_passwordTextBoxKeyPressed

    private void usernameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextBoxKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            boolean verify = false;
            String user = usernameTextBox.getText();
            String passwd = passwordTextBox.getText();
            if (user.equals("") || passwd.equals("")) {
                JOptionPane.showMessageDialog(AcctLogin.this, "Sorry! You must enter a Username and Password to login ");
                usernameTextBox.requestFocus();
            } else {
                Connection con = getConnection();
                try {
                    ResultSet rows;
                    Statement s = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    String select = "Select * from teacherLogin";
                    rows = s.executeQuery(select);
                    while (rows.next()) {
                        String username = rows.getString("Username");
                        String password = rows.getString("Password");
                        if (user.equals(username) && passwd.equals(password)) {
                            verify = true;
                            this.dispose();
                            JFrame frame = new JFrame();
                            AdminMainView teacherBtns = new AdminMainView();
                            teacherBtns.teacherBtnsEnabled();
//                        new QtityWindow2().setVisible(true);
//                        JFrame frame1 = new JFrame();
//                        TeacherForm form = new TeacherForm(frame1,"School Management System");
//                        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
//                        form.setLocation((screen.width - 1160)/2,((screen.height-700)/2));
//                        form.setVisible(true);
                            break;
                        }
                    }
                    if (verify == false) {
                        verify = false;
                        JOptionPane.showMessageDialog(AcctLogin.this, "Access Denied!  Invalid Username or Password");
                        usernameTextBox.setText("");
                        passwordTextBox.setText("");
                        usernameTextBox.requestFocus();
                    }
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
                if (verify == false) {
                    JOptionPane.showMessageDialog(AcctLogin.this, "Access Denied!  Invalid Username or Password");
                    usernameTextBox.setText("");
                    passwordTextBox.setText("");
                    usernameTextBox.requestFocus();
                }     // TODO add your handling code here:
            }

        }

        if (key == KeyEvent.VK_DOWN) {
            passwordTextBox.grabFocus();
        }
        if (key == KeyEvent.VK_KP_DOWN) {
            passwordTextBox.grabFocus();
        }
    }//GEN-LAST:event_usernameTextBoxKeyPressed

    private void passwordTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //JFrame frame1= new JFrame();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        AccessControl accessControlForm = new AccessControl();
        accessControlForm.setLocation((screen.width - 400) / 2, ((screen.height - 350) / 2));
        accessControlForm.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
//                JFrame frame1= new JFrame();
//                 AcctLogin form = new AcctLogin(frame1,"School Management System");
//                 form.setVisible(true);
//                 form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordTextBox;
    private javax.swing.JTextField usernameTextBox;
    // End of variables declaration//GEN-END:variables
}
