/*
 *
 */
package com.ourteam.yippySMS.view;

import com.ourteam.yippySMS.controller.DefaultAdmissionController;
import com.ourteam.yippySMS.helpers.ManagePicture;
import com.ourteam.yippySMS.model.Person;
import com.ourteam.yippySMS.model.Person.Gender;
import java.awt.Dialog;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.Document;

/**
 *
 * @author danteata
 */
public class StudentAdmissionPanel extends AbstractViewPanel {

	private DefaultAdmissionController controller;
	private ArrayList<String> cardNames = new ArrayList<String>();

	public ArrayList<String> getCardNames() {
		return cardNames;
	}

	public DefaultAdmissionController getController() {
		return controller;
	}

//	public JPanel getAdmissionDisplayCard() {
//		return admissionDisplayCard;
//	}
//	public StudentAdmissionDisplayPanel getAdmissionDisplayView() {
//		return (StudentAdmissionDisplayPanel)admissionDisplayView;
//	}
	/**
	 * Creates new form StudentAdmissionPanel
	 * @param controller An object implementing the controller interface that
	 *        this view can use to process GUI actions
	 */
	public StudentAdmissionPanel(DefaultAdmissionController controller) {

		this.controller = controller;

		initComponents();
//        localInitialization();

	}

	// </editor-fold>
	// <editor-fold defaultstate="collapsed" desc=" Model Event Handling Code ">
	/**
	 * Called by the controller when it needs to pass along a property change
	 * from a model. Note that the method checks each GUI parameter to determine
	 * if the current value is already equal to the incoming value. If it is, 
	 * the method will not reset the value. This is done to prevent looping from
	 * occurring when a model property is reset.
	 * @param evt The property change event
	 */
	public void modelPropertyChange(final PropertyChangeEvent evt) {


		if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_FNAME_PROPERTY)) {

			String newStringValue = evt.getNewValue().toString();

//            if (!fNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                fNameLabel.setText(newStringValue);

		} else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_MNAME_PROPERTY)) {

			String newStringValue = evt.getNewValue().toString();

//            if (!fNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                fNameLabel.setText(newStringValue);

		} else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_LNAME_PROPERTY)) {

			String newStringValue = evt.getNewValue().toString();

//            if (!lNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                lNameLabel.setText(newStringValue);

		} else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_DOB_PROPERTY)) {

			String newStringValue = evt.getNewValue().toString();

//            if (!DOBLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                DOBLabel.setText(newStringValue);
		}
	}

	// </editor-fold>  
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider2 = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();
        sImageChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fNameTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mNameTextBox = new javax.swing.JTextField();
        lNameTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox(Person.Gender.values());
        religionLabel = new javax.swing.JLabel();
        formerSchoolTitleLabel = new javax.swing.JLabel();
        formerSchoolTextBox = new javax.swing.JTextField();
        religionCombo = new javax.swing.JComboBox();
        DOBChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addStudentButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        sUploadImgBtn = new javax.swing.JButton();
        sImageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(90, 191, 242));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTextBoxActionPerformed(evt);
            }
        });
        fNameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameTextBoxFocusLost(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Middle Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Gender");

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        religionLabel.setText("Religion");

        formerSchoolTitleLabel.setText("Former School");

        religionCombo.setEditable(true);
        religionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christian", "Muslim", "Traditional" }));

        jLabel11.setText("Date of Birth");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        sUploadImgBtn.setText("Upload Image");
        sUploadImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUploadImgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sUploadImgBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sUploadImgBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(religionLabel)
                                        .addComponent(formerSchoolTitleLabel)
                                        .addComponent(jLabel11))
                                    .addGap(29, 29, 29))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DOBChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(mNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(fNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(sImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(gender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(religionCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 174, Short.MAX_VALUE)))
                                .addGap(31, 31, 31))
                            .addComponent(formerSchoolTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(religionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(religionLabel)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOBChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(formerSchoolTitleLabel)
                                .addGap(6, 6, 6))
                            .addComponent(formerSchoolTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(sImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addStudentBanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(775, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
		// TODO add your handling code here:}//GEN-LAST:event_genderActionPerformed
	}

		private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
			if (fNameTextBox.getText().isEmpty() || lNameTextBox.getText().isEmpty() || gender.getSelectedItem() == null) {
				JOptionPane.showMessageDialog(null, "Please fill out required fields first", "Warning Message", JOptionPane.WARNING_MESSAGE);
				this.fNameTextBox.requestFocus();
			} else {
				//collecting user inputs
				String fName = fNameTextBox.getText();
				String mName = mNameTextBox.getText();
				String lName = lNameTextBox.getText();
				String religion = (String) religionCombo.getSelectedItem();
				Gender genderOption = (Gender) gender.getSelectedItem();
				Date dob = DOBChooser.getDate();
			File file = sImageChooser.getSelectedFile();

			//assigns null if no image loaded or byte converted image from file if otherwise
			byte[] imageInBytes = (file == null) ? null : ManagePicture.readBytesFromFile(file);	
				//			String contactNo = contactNumberTextBox.getText();
				//			Subject preferredSubject = (Subject) preferredSubjectComboBox.getSelectedItem();
				//returns true on successful addition 
				boolean isAdmitted = controller.handleAddStudent(fName, mName, lName, religion, "", genderOption, dob, null, imageInBytes);

				if (isAdmitted) {
					this.clearButton.doClick();

					JOptionPane.showMessageDialog(null, "Student added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
				} else {

					JOptionPane.showMessageDialog(null, "Unable to add Teacher", "Information", JOptionPane.INFORMATION_MESSAGE);
				}
		}//GEN-LAST:event_addStudentButtonActionPerformed
	}
		private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		// TODO add your handling code here: 		this.dispose(); 	}//GEN-LAST:event_cancelButtonActionPerformed
	}
		private void fNameTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameTextBoxFocusLost
			// TODO add your handling code here:
	}//GEN-LAST:event_fNameTextBoxFocusLost

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
		// TODO add your handling code here:
		this.fNameTextBox.setText("");
		this.mNameTextBox.setText("");
		this.lNameTextBox.setText("");
		this.gender.setSelectedItem("");
		//this.physicalAddressTextBox.setText("");
		//this.boxAddressTextBox.setText("");
		this.formerSchoolTextBox.setText("");
		// this.assignedClassCombo.setSelectedItem("");
		//this.contactNumberTextBox.setText("");
		//this.contactNumberTextBox.setText("");
		this.fNameTextBox.requestFocus();
	}//GEN-LAST:event_clearButtonActionPerformed

	private void fNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTextBoxActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_fNameTextBoxActionPerformed

	private void sUploadImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUploadImgBtnActionPerformed
		// TODO add your handling code here:
		int returnVal = sImageChooser.showOpenDialog(this);
	if (returnVal == JFileChooser.APPROVE_OPTION) { 		
		File file = sImageChooser.getSelectedFile(); 			 	
		byte[] sImage = ManagePicture.readBytesFromFile(file);
		sImageLabel.setIcon(new ImageIcon(sImage));
	} else { 			
		// ... 	
	}	
	}//GEN-LAST:event_sUploadImgBtnActionPerformed
	// </editor-fold>
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOBChooser;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField fNameTextBox;
    private javax.swing.JTextField formerSchoolTextBox;
    private javax.swing.JLabel formerSchoolTitleLabel;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField lNameTextBox;
    private javax.swing.JTextField mNameTextBox;
    private javax.swing.JComboBox religionCombo;
    private javax.swing.JLabel religionLabel;
    private javax.swing.JFileChooser sImageChooser;
    private javax.swing.JLabel sImageLabel;
    private javax.swing.JButton sUploadImgBtn;
    // End of variables declaration//GEN-END:variables
}
