/*
 *
 */

package com.ourteam.yippySMS.view;

import com.ourteam.yippySMS.controller.DefaultAdmissionController;
import com.ourteam.yippySMS.model.Person;
import com.ourteam.yippySMS.model.Person.Gender;
import com.ourteam.yippySMS.model.Staff;
import com.ourteam.yippySMS.model.Staff.Status;
import com.ourteam.yippySMS.helpers.ImageFilter;
import com.ourteam.yippySMS.helpers.ManagePicture;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author danteata
 */

public class TeacherAdmissionPanel extends AbstractViewPanel
{
    
    //  The controller used by this view
    
    private DefaultAdmissionController controller;
    
    //  A local copy of the current Font which can be passed to the 
    //  constructor of JFontChooserDialog.
    
    
    
    /**
     * Creates new form StudentAdmissionPanel
     * @param controller An object implementing the controller interface that
     *        this view can use to process GUI actions
     */
    public TeacherAdmissionPanel(DefaultAdmissionController controller) {
        
        this.controller = controller;
        
        initComponents();
//        localInitialization();
        
    }

  
    
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc=" Model Event Handling Code ">

    /**
     * Called by the controller when it needs to pass along a property change
     * from a model. Note that the method checks each GUI parameter to determine
     * if the current value is already equal to the incoming value. If it is, 
     * the method will not reset the value. This is done to prevent looping from
     * occurring when a model property is reset.
     * @param evt The property change event
     */
    
    public void modelPropertyChange(final PropertyChangeEvent evt) {
          
            
        if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_FNAME_PROPERTY)) {
            
            String newStringValue = evt.getNewValue().toString();
            
//            if (!fNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                fNameLabel.setText(newStringValue);
            
        }
	else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_MNAME_PROPERTY)) {
            
            String newStringValue = evt.getNewValue().toString();
            
//            if (!fNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                fNameLabel.setText(newStringValue);
            
        }
	else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_LNAME_PROPERTY)) {
            
            String newStringValue = evt.getNewValue().toString();
            
//            if (!lNameLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                lNameLabel.setText(newStringValue);
            
        }	
	else if (evt.getPropertyName().equals(DefaultAdmissionController.STUDENT_DOB_PROPERTY)) {
            
            String newStringValue = evt.getNewValue().toString();
            
//            if (!DOBLabel.getText().equals(newStringValue))// checks to see if there is truely a property change
//                DOBLabel.setText(newStringValue);
        }	
    }   

    // </editor-fold>  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider2 = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tImageChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fNameTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mNameTextBox = new javax.swing.JTextField();
        lNameTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genderCombo = new javax.swing.JComboBox(Person.Gender.values());
        religionLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contactNoTextBox = new javax.swing.JTextField();
        religionCombo = new javax.swing.JComboBox();
        DOBChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addTeacherButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        tUploadImageBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox(Staff.Status.values());
        tImageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        tImageChooser.setDialogTitle("Select Image");
        tImageChooser.setFileFilter(new ImageFilter());

        setBackground(new java.awt.Color(90, 191, 242));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fNameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameTextBoxFocusLost(evt);
            }
        });

        jLabel2.setText("First Name");

        jLabel3.setText("Middle Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Gender");

        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        religionLabel.setText("Religion");

        jLabel8.setText("Contact No");

        contactNoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNoTextBoxActionPerformed(evt);
            }
        });

        religionCombo.setEditable(true);
        religionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Christian", "Muslim", "Traditional", " " }));

        jLabel11.setText("Date of Birth");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        addTeacherButton.setText("Add Teacher");
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        tUploadImageBtn.setText("Upload Picture");
        tUploadImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUploadImageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(tUploadImageBtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTeacherButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tUploadImageBtn))
                .addContainerGap())
        );

        jLabel7.setText("Marital Status");

        statusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mNameTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(religionLabel)
                                    .addComponent(jLabel8))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DOBChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(religionCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 174, Short.MAX_VALUE)
                                                    .addComponent(genderCombo, 0, 174, Short.MAX_VALUE))
                                                .addGap(19, 19, 19))))
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(tImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(mNameTextBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lNameTextBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(religionLabel)
                    .addComponent(religionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOBChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contactNoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addTeacherBanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(975, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed

		// TODO add your handling code here:}//GEN-LAST:event_genderComboActionPerformed
	}

		private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed


		if (fNameTextBox.getText().isEmpty() || lNameTextBox.getText().isEmpty() || genderCombo.getSelectedItem() == null) {
			JOptionPane.showMessageDialog(null, "Please fill out required fields first", "Warning Message", JOptionPane.WARNING_MESSAGE);
			this.fNameTextBox.requestFocus();
		} else {
			//collecting inputs by user
			String fName = fNameTextBox.getText();
			String mName = mNameTextBox.getText();
			String lName = lNameTextBox.getText();
			String religion = (String) religionCombo.getSelectedItem();
			Gender genderOption = (Gender) genderCombo.getSelectedItem();
			Status status = (Status) statusCombo.getSelectedItem();
			Date dob = DOBChooser.getDate();
			String contactNo = contactNoTextBox.getText();

			File file = tImageChooser.getSelectedFile();

			//assigns null if no image loaded or byte converted image from file if otherwise
			byte[] imageInBytes = (file == null) ? null : ManagePicture.readBytesFromFile(file);	
	
//			Subject preferredSubject = (Subject) preferredSubjectComboBox.getSelectedItem();
//controller.handleAddStudent(fName, mName, lName, religion, contactNo, genderOption, dob, null);
			
			//assigns true if successful 
			boolean addStatus = controller.handleAddTeacher(fName, mName, lName, religion, contactNo, genderOption, status, dob, imageInBytes);
			
			if(addStatus){
			this.clearButton.doClick();  // clear input fields 
			
			JOptionPane.showMessageDialog(null, "Teacher added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
			}else{
				
			JOptionPane.showMessageDialog(null, "Unable to add Teacher", "Information", JOptionPane.INFORMATION_MESSAGE);
			}
		}//GEN-LAST:event_addTeacherButtonActionPerformed
		}
		private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

		// TODO add your handling code here: 		this.dispose(); 	}//GEN-LAST:event_cancelButtonActionPerformed
		}
		private void fNameTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameTextBoxFocusLost
		// TODO add your handling code here:
			controller.changeStudentFName(fNameTextBox.getText());
			
	}//GEN-LAST:event_fNameTextBoxFocusLost

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
		// TODO add your handling code here:
	     this.fNameTextBox.setText("");
             this.mNameTextBox.setText("");
             this.lNameTextBox.setText("");
             this.genderCombo.setSelectedItem(null);
	     this.religionCombo.setSelectedItem(null); 
	     this.statusCombo.setSelectedItem(null); 
	     this.DOBChooser.cleanup();
        //this.physicalAddressTextBox.setText("");
        //this.boxAddressTextBox.setText("");
//        this.subjectAreaTextBox.setText("");
       // this.assignedClassCombo.setSelectedItem("");
             this.contactNoTextBox.setText("");
             this.fNameTextBox.requestFocus();	
	}//GEN-LAST:event_clearButtonActionPerformed

	private void statusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_statusComboActionPerformed

	private void tUploadImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUploadImageBtnActionPerformed
		// TODO add your handling code here:
	int returnVal = tImageChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) { 		
		File file = tImageChooser.getSelectedFile(); 			 	
		byte[] tImage = ManagePicture.readBytesFromFile(file);
		tImageLabel.setIcon(new ImageIcon(tImage));
	} else { 			
		// ... 	
	}	
   
	}//GEN-LAST:event_tUploadImageBtnActionPerformed

private void contactNoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNoTextBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_contactNoTextBoxActionPerformed
			
			
    
    // </editor-fold>
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOBChooser;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField contactNoTextBox;
    private javax.swing.JTextField fNameTextBox;
    private javax.swing.JComboBox genderCombo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField lNameTextBox;
    private javax.swing.JTextField mNameTextBox;
    private javax.swing.JComboBox religionCombo;
    private javax.swing.JLabel religionLabel;
    private javax.swing.JComboBox statusCombo;
    private javax.swing.JFileChooser tImageChooser;
    private javax.swing.JLabel tImageLabel;
    private javax.swing.JButton tUploadImageBtn;
    // End of variables declaration//GEN-END:variables
    
}
